### ISSUE TITLE
How to pass build system options?

### ISSUE THREAD

**Issue by ff2000** [rdnetto/YCM-Generator#1]
I need to pass configure options to an autotools-based project to disable a feature that seems to be hard-enabled - configure fails if a dependency can't be found.
In this case it already would help if the simple "found Makefile" case could be used in the first place (IMHO would make sense in any case) as "autotools" and "cmake" will create a functional Makefile.
Or give a CMDLine option to forcefully select a generator?

Furthermore YCM-Generator seems to be "destructive" - it runs make clean and cleans up a perfectly fine configured build environment.

**Comment by rdnetto** [comment]
In the case of autotools projects, the compiler is set during the configure stage. Since YCM-Gen works by setting a 'fake' compiler, that needs to be repeated - simply reusing the existing Makefile wouldn't work. Once the flags have been collected, we then need to run ```make maintainer-clean``` to delete the configuration files, because otherwise the generated makefiles would call the fake compiler.

The only way to make the process completely non-destructive is to use out-of-tree builds. I didn't do this originally for autotools since apparently not all projects support this, but it's probably a good idea to support it.

Adding an option to specify config options is also a good idea - I'll try and get 'round to it sometime in the next week.

**Comment by rdnetto** [comment]
I've pushed the changes to the develop branch - can you verify these work as required?

**Comment by ff2000** [comment]
There is an issue when the directory is already configured:

```configure: error: source directory already configured; run "make distclean" there first```

I think running "make distclean" if --out-of-tree is set should fix the issue.

And a question: How to pass arguments from within vim? As far as I can see YcmGenerateConfig doesn't handle args at all, so I would say it does not work (yet), am I right?

**Comment by rdnetto** [comment]
That defeats the point of using --out-of-tree though, because it'll delete the existing configuration. Until you run ./configure, no makefile exists in the temporary directory, so you can only run it in the source directory. AIUI, this means that --out-of-tree is only usable if you do your own builds out-of-tree as well, since otherwise they'll step on each others' toes. In practice, this won't be too much of an issue I think, since most people will (hopefully) generate the config before attempting to configure & compile the project. I can't really see anyway around it except to copy the entire source directory, and I definitely want to avoid that since it could easily be larger than /tmp.

Passing arguments from within Vim is something I meant to do, and then promptly forgot about. I should have it uploaded shortly.
