### ISSUE TITLE
The line parser ignores critical cmake output

### ISSUE THREAD

**Issue by RomanHargrave** [rdnetto/YCM-Generator#11]
This is partially due to intended behaviour.

I am currently working on a rather [large cmake project](http://github.com/skyjake/doomsday-engine). 
When building, CMake builds individual objects and then links them all. The necessary compiler flags are passed only during compilation of the temporary objects. As such, few lines are read, none of which contain any flags that are useful for YCM-Generator.

I fixed this by disabling the temporary output exclusion.

**Comment by rdnetto** [comment]
Ok, it looks like all of those lines are being skipped because they contain the `-E` flag, which only performs the preprocessing step. The reason I added `-E` to the blacklist in the first place was to filter out some files in the Linux kernel build process, but it looks like the other regexes in that list are sufficient for that, so there aren't any issues with removing it.
