### ISSUE TITLE
Compatible with Conan

### ISSUE THREAD

**Issue by bchirva** [rdnetto/YCM-Generator#123]
On Linux systems Ycm-Generator runnig CMake in temporary directory (/tmp/...), so if we use [Conan](https://conan.io/) for dependency management, generator throw an error, because it couldn't open & include conanbuildinfo.cmake, generated by conan and located in user's project build directory (for example, some_project_root_dir/build).
So, suggestion is think about flag for force run CMake (or/and diffent build systems) in current working directory.
Thanks.
P.S. Sorry for poor English.

**Comment by rdnetto** [comment]
Running cmake in the same working directory is generally not safe, since it will mutate the existing build files to use the fake toolchain, and prevent them from building the project correctly. This is why we use out-of-tree builds where possible, which correctly implemented Cmake projects should support.

As I understand it, Cmake has the ability to specify that certain files need to be copied into the build directory - I suspect this is what you need to use to fix your build.

**Comment by bchirva** [comment]
Here's the thing. Conan generates project configuration files (with list of include directories and libraries to link) in build directory. Build system is not matter, it can be CMake, qmake or something else. Anyway you can't know (and specify) the path to build folder (like ${CMAKE_BINARY DIR} for CMake or $$OUT_PWD for qmake) to copy files from there, because your (and user's) build directory can be anywhere on file system.
As I see, any solutions (at least obvious solutions) to solve this problem is conflict with YCM-generator logic, so I close issue. 

P.S. Conan is not so common tool today, but if it will become popular, then its compatible with YCM-generator will become serious problem.
Regards.
