### ISSUE TITLE
Support of Android.mk and Application.mk files

### ISSUE THREAD

**Issue by f-squirrel** [rdnetto/YCM-Generator#23]
Hi,

I like your plugin very much and use it with makefiles.
Do you have any plans for support of Android build system(Android.mk, Application.mk)?

**Comment by rdnetto** [comment]
No, not at this point. In general I try to avoid adding support for tools I haven't used, since I don't have the experience to know what the standard use cases and good practices are.

However, if someone were to write a patch/pull request that adds that functionality, I'd be happy to merge and support it. (See the qmake PR for an example of this.)
