### ISSUE TITLE
Linux Kernel Flags

### ISSUE THREAD

**Issue by jdiefen** [rdnetto/YCM-Generator#30]
Hi,
I've been trying to use YCM for Yocto Project's linux kernel source code. From what I read, this generator is tested against the kernel source (not quite the same as Yocto's, but should be close...).  
I've been trying to use this tool in the top directory of the source code, and the config file _does_ generate. However, it seems there's alot missing... Just opening `kernel/exit.c` has YCM throwing a bunch of errors about things not being defined/etc.

Here's all the output:

``` bash
~/Code/linux(hw1 ✔) ~/.vim/plugged/YCM-Generator/config_gen.py ~/Code/linux/ --preserve-environment
'/home/jadin/Code/linux/.ycm_extra_conf.py' already exists. Overwrite? [y/N] y
 Preparing build directory...
$ make clean

Running make...
$ make -i -j4
Build completed in 6.09 sec

WARNING: 232 distinct definitions of macro KBUILD_MODNAME found
WARNING: 232 distinct definitions of macro KBUILD_BASENAME found
Collected 288 relevant entries for C compilation (176 discarded).
Collected 0 relevant entries for C++ compilation (0 discarded).
Created YCM config file with 54 C flags
```

Using the newest source from git://git.yoctoproject.org/linux-yocto-3.14, tag `v3.14.26`.

Is this tool not going to work for me? Or am I missing some necessary option?

Thanks!

**Comment by rdnetto** [comment]
I've reproduced the problem with the mainline kernel, so it's not just Yocto.

What this comes down to is that while YCM-Gen generates a _mostly_ correct config file, YCM itself doesn't actually handle the Linux kernel correctly (partly because the kernel doesn't fully support clang yet). That said, the omnicompletion does actually work for the most part (I'm not aware of it missing anything), it's just that you get a lot of implicit declaration errors in the process. The best option is to just edit `.ycm_config.py` to suppress those errors.
