### ISSUE TITLE
Release, master

### ISSUE THREAD

**Issue by Yamakaky** [rdnetto/YCM-Generator#35]
You doesn't seem to use `master`. Maybe you should delete it ?
Do you plan to do a release, like 0.1 or 1.0 ?

**Comment by rdnetto** [comment]
Woops, I should have deleted that back in March when I changed the branching model. Fixed.

**Comment by Yamakaky** [comment]
And for the release ? It's better for the users, as it indicates when things break.

**Comment by rdnetto** [comment]
There's already a system in place for that - changes happen on the `develop` branch, and are merged to the `stable` branch when I consider them to be ready (e.g. when I stop getting bug reports from `develop` beta users).

I don't have any versioning in place atm, but that's not particularly important since there isn't anything trying to be compatible with YCM-Gen, nor do most Vim plugin managers require it.

Breakage should ideally be limited to the `develop` branch - I think I've only had one case in the last half year where a `stable` push resulted in bug reports. Users who are concerned about the possibility of breakage should simply refrain from upgrading immediately after a release, but releases are logged in the commit log as merges anyway - I don't see what versioning would offer over that.
