### ISSUE TITLE
ERROR: Unknown build system

### ISSUE THREAD

**Issue by rmporsch** [rdnetto/YCM-Generator#36]
I get the following error:

```
ERROR: Unknown build system
```

after running 

```
~/.vim/bundle/YCM-Generator/config_gen.py --verbose --compiler clang-3.6 .
```

on 

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
```

**Comment by rdnetto** [comment]
Please run `ls` in the project directory and post the output. Also, what build system does the project use?

**Comment by rmporsch** [comment]
fixed it. `CMakeLists.txt` was gone for some reason. Now the error is 

```
ERROR: No commands were logged to the build logs (C: /tmp/tmpTqblcZ, C++: /tmp/tmpguQm45).
Your build system may not be compatible.
```

I assume this corresponds to issue #3, and I will need to downgrade my clang

Sorry for the stupid mistake.

**Comment by rdnetto** [comment]
No problem, I've made more than my share of stupid mistakes. :P

Make sure there's no Makefile in the directory, otherwise it'll override the settings for the fake toolchain.

Note also that the fix for #3 is _not_ to downgrade clang, but to specify the actual name of the compiler using `--compiler`. (Alternatively, you could just create a symlink called `clang` to the actual executable.)

**Comment by rmporsch** [comment]
thanks a lot! Works now!

**Comment by pBlasiak** [comment]
Hi rdnetto
I am trying to use ycm-generator for OpenFOAM.
I compiled ycm according to this
https://github.com/Valloric/YouCompleteMe#full-installation-guide

I typed the following
./config_gen.py -v -e -c ~/ycm_temp/llvm_root_dir/bin/clang ~/OpenFOAM/OpenFOAM-v1612+/

but I got the error:
ERROR: Unknown build system
