### ISSUE TITLE
No errors, but not getting proper completion suggestions

### ISSUE THREAD

**Issue by ArchdukeChocula** [rdnetto/YCM-Generator#41]
Hello, I'm new to Linux and having an issue getting YCM to work. I can't tell if I'm screwing up something on the YCM end, or the YCM-Generator end. I'm running it all on Ubuntu 14.04. 

I followed the instructions on the YCM page for the full install originally, but I was having trouble with clang, so I swapped to using vundle instead of pathogen and followed the shorter vundle instructions on the YCM page.

I'm at a point where nothing is giving me errors, but I'm still not getting the completion suggestions that I would expect. For example, "#include <std " pulls up Intrin.h and altivec.h, but not stdlib.h. It's also saying "User defined completion (U^N^P)" all the time.

I have my base directory 'Code' with 'C' as a subdirectory, and 'HelloWorld.c' as the file I'm trying to work with. Here's my CMake files:

CMakeLists.txt in 'Code'

```
cmake_minimum_required(VERSION 2.7)
project(CODE)

set((CMAKE_CXX_FLAGS "-g -Wall")
add_subdirectory(C)
```

CMakeLists.txt in 'C'

```
include_directories($(CODE_SOURCE_DIR)/C)
link_directories($(CODE_BINARY_DIR)/C)

add_executable(helloworld HelloWorld.c)
```

The .ycm_extra_conf.py that was generated is long, so here's a link to it with the comments excluded.
[Link to .ycm_extra_conf.py](https://gist.github.com/ArchdukeChocula/ae669d27db60be6201db)

Let me know if there's somewhere better to ask this. Like I said, still new!

**Comment by rdnetto** [comment]
> I followed the instructions on the YCM page for the full install originally, but I was having trouble with clang

Can you be more specific? If clang isn't working / able to compile your project, than YCM probably won't work either.

The thing that jumps out at me is that the flags `-g -Wall` aren't making it into the conf file. That suggests that either you're not setting them correctly (compile the project from the terminal and check if they're being used), or that YCM-Gen isn't picking them up. It's hard to say which without seeing the output from running `config_gen.py -v .`, but one very common mistake people run into with cmake is not using out of tree builds. If you try to compile by running `cmake . && make`, then the resulting makefiles will override the environment variables when YCM-Gen tries to run it through the fake toolchain. You should be generating the Makefiles in a separate directory to avoid this.

**Comment by ArchdukeChocula** [comment]
> Can you be more specific? If clang isn't working / able to compile your project, than YCM probably won't work either.

Sure thing, when I was doing the "full install instructions" I downloaded clang+llvm from the [clang site](http://clang.llvm.org/get_started.html), then waited a couple hours for it to build. I'm on a chromebook with limited space, so the 4 gig install was an issue. I removed it and downloaded through sudo apt-get clang instead and I now can compile things through the clang command, but I had already removed the YCM progress to start fresh, so I went through the install script the second time around.

[Here's the config -v.](https://gist.github.com/anonymous/c01bf6976a43e4dfe57b) I could be generating the makefiles incorrectly, I'll try again how you said.

EDIT: I had followed [this guide](http://www.cs.swarthmore.edu/~adanner/tips/cmake.php) so I had a separate build directory just under my project root. That page said to run cmake .. and then make in the build directory, should I be running make somewhere else?

EDIT 2: I was getting an error when trying to make this time that said I needed to compile with -std=c99. I added it to the flags in the root CMakeLists.txt and it was still erroring though, so I changed "set(CMake_CXX" to "set(Cmake_C" and it worked. My .ycm config now is generating with all of the flags except -g.

```
flags = [
        '-x',
        'c',
        '-I/home/michael/Code/C//C',
        '-Wall',
        '-std=c99'.
]
```

Still no luck on YCM working right, though.

Edit 3: Added some lines to the config on someone else's suggestion and it worked for the suggestions in the includes. Still not getting proper suggestions for the rest of it, though.

```
'-isystem',
'/usr/include',
```

**Comment by rdnetto** [comment]
Ok, so it looks like cmake is running correctly as an out of tree build, and you're using clang 3.4. You're working in C, which is why you need to set CMAKE_C instead of CMAKE_CXX  (which would be for C++). YCM-Gen is collecting the flags correctly from the compilation process, and YCM is doing omnicompletion as instructed, but there are issues in how you're specifying them to cmake.

In a nutshell, the problem is with your build (i.e. cmake files). If it doesn't even compile correctly normally, then there's not much YCM-Gen can do. My understanding is that the `-isystem` flag will normally be added by cmake somehow, probably by using one of it's predefined templates / library definitions / whatever. Unfortunately, I don't know enough about cmake to help you further, since of the supported build systems it's the one I'm least familiar with. I suggest you ask for help on one of their [mailing lists](https://cmake.org/mailing-lists/) - someone there should be able to help you.

As an aside, cmake is easily one of the more complex / powerful build systems. I don't know how much experience you have with C programming, but if you're a beginner then depending on the size of your project you might want to consider using Makefiles instead. They're not as portable or fancy, but for simple cases they're a lot easier to write (since they're not that different to bash scripts).

**Comment by ArchdukeChocula** [comment]
I found the issue but I still haven't been able to solve it. Since it isn't a YCM-Gen problem I'll close this, though. Thanks for the help!

**Comment by rdnetto** [comment]
No problem. Hope you figure it out. :)
