### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by EntilZha** [rdnetto/YCM-Generator#44]
I am trying to generate a config file for the code here: https://github.com/EntilZha/GrappaRDD. The makefile there references a Makefile generated from the project here: https://github.com/EntilZha/grappa. This is being executed on a clean Linux Mint 17 VM.

If I run `make -i -j2` from the shell I get the following (correct) output and a program:

```
pedro@terminus /media/sf_Code/GrappaRDD $ make clean
rm -f main.o main
pedro@terminus /media/sf_Code/GrappaRDD $ make
/usr/bin/g++ -DENABLE_RDMA_AGGREGATOR  -std=c++11 -Winline -Wno-inline -mno-red-zone  -O3 -g -DNDEBUG -I/home/pedro/dependencies/grappa/build/Make+Release/install/include -I/home/pedro/dependencies/grappa/build/Make+Release/install/include/Grappa -I/home/pedro/dependencies/grappa/build/Make+Release/install/include/Grappa/tasks -I/usr/local/include   -c -o main.o main.cpp
/usr/bin/g++ -Wl,-rpath  -Wl,/usr/local/lib  -Wl,--enable-new-dtags  -L/home/pedro/dependencies/grappa/build/Make+Release/install/lib -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu  main.o  -Wl,-Bstatic -lGrappa -lglog -lgflags -lgraph500-generator -lboost_system -lboost_filesystem -Wl,-Bdynamic -lmpicxx -lmpi -lpthread -lrt -o main
```

However, when I run `~/.vim/bundle/YCM-Generator/config_gen.py -v -e .` I get

```
pedro@terminus /media/sf_Code/GrappaRDD $ ~/.vim/bundle/YCM-Generator/config_gen.py -v -e .
Preparing build directory...
$ make clean
rm -f main.o main

Running make...
$ make -i -j2
/usr/bin/g++ -DENABLE_RDMA_AGGREGATOR  -std=c++11 -Winline -Wno-inline -mno-red-zone  -O3 -g -DNDEBUG -I/home/pedro/dependencies/grappa/build/Make+Release/install/include -I/home/pedro/dependencies/grappa/build/Make+Release/install/include/Grappa -I/home/pedro/dependencies/grappa/build/Make+Release/install/include/Grappa/tasks -I/usr/local/include   -c -o main.o main.cpp
/usr/bin/g++ -Wl,-rpath  -Wl,/usr/local/lib  -Wl,--enable-new-dtags  -L/home/pedro/dependencies/grappa/build/Make+Release/install/lib -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu  main.o  -Wl,-Bstatic -lGrappa -lglog -lgflags -lgraph500-generator -lboost_system -lboost_filesystem -Wl,-Bdynamic -lmpicxx -lmpi -lpthread -lrt -o main
g++: error: main.o: No such file or directory
make: [main] Error 1 (ignored)
Build completed in 4.14 sec

Collected 0 relevant entries for C compilation (0 discarded).
Collected 0 relevant entries for C++ compilation (0 discarded).
()
ERROR: No commands were logged to the build logs (C: /tmp/tmpGRwJep, C++: /tmp/tmp8JlxNM).
Your build system may not be compatible.
```

I understand what that error (missing file), but I don't know why it happens only when I run the generate script. Any ideas?

**Comment by rdnetto** [comment]
Looking at the `grappa` repo, it appears to use cmake (indirectly, via the configure script). The problem is that once cmake generates a Makefile, that Makefile has the compiler hardcoded. YCM-Gen relies on being able to override the compiler (via the `CC` / `CXX` variables).

I think the best approach would be to eliminate the dependency on the generated makefile by converting `GrappaRDD` to use cmake. (I assume cmake has some native way of including other cmake files). That way it's generated with the compiler variables set correctly.

An alternative (easier) approach would be to just generate the config file for `grappa`, then copy it into the `GrappaRDD` folder with some minor changes.

**Comment by EntilZha** [comment]
I originally was using cmake for `GrappaRDD`, but couldn't figure out how to include the `grappa.mk` file which configures my code to link against Grappa. If you know how to do that, would be great since I am fairly new to make/cmake with C/C++.

I will try your second suggestion, that seems like it might work pretty easily since `GrappaRDD` doesn't have any external dependencies.

**Comment by rdnetto** [comment]
Based on the output of make, my guess is you could add something like this to the makefile:

```
LDFLAGS="-Wl,-rpath  -Wl,/usr/local/lib  -Wl,--enable-new-dtags  -L$(GRAPPA_PREFIX)/build/Make+Release/install/lib -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu"
LDLIBS="-lGrappa -lglog -lgflags -lgraph500-generator -lboost_system -lboost_filesystem -Wl,-Bdynamic -lmpicxx -lmpi -lpthread -lrt"

all: main
main: main.o
main.o: RDD.hpp GrappaContext.hpp
    $(CXX) -c $(CPPFLAGS) $(CXXFLAGS)
```

into the Makefile.

I suggest reading the docs on [implicit rules](https://ftp.gnu.org/old-gnu/Manuals/make-3.79.1/html_chapter/make_10.html) and [variables](https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html), since they explain what's happening behind the scenes.

You could also just copy and paste the line from the makefile (replacing `g++` with `$(CXX)`) but that's less maintainable.
