### ISSUE TITLE
append default flags 

### ISSUE THREAD

**Issue by agauniyal** [rdnetto/YCM-Generator#45]
Provide an option to append some flags since it works on per project basis. eg. I would like to append these flags in front of my .ycm file

```
'-Wall',
'-Wextra',
'-Wno-variadic-macros',
'-fexceptions',
'-DNDEBUG',
'-DUNIT_TESTS',
'-std=c++11',
'-x', 'c++',
'-isystem', '/home/sehe/custom/boost',
'-isystem', '/usr/lib/gcc/x86_64-linux-gnu/4.8/include',
'-I', 'src',
'-I', 'include',
'-isystem', '/usr/include',
'-isystem', '/usr/local/include', 
```

**Comment by rdnetto** [comment]
YCM-Gen generates a list of flags from the project's makefile. Adding flags to the config file will change the errors shown in Vim, but it won't do anything to alter the actual compilation of the project, and IMO it's best to have the flags in `.ycm_extra_conf.py` match those of the Makefile as closely as possible.

So, what exactly is the use case for adding flags that are not present in the project's makefile?

**Comment by agauniyal** [comment]
```
'-isystem', '/home/custom/boost',
'-isystem', '/usr/lib/gcc/x86_64-linux-gnu/4.8/include',
'-isystem', '/usr/include',
'-isystem', '/usr/local/include',
```

are needed for non-project based completion ie. cpp standard, header files etc.

**Comment by agauniyal** [comment]
https://github.com/Valloric/YouCompleteMe#completion-doesnt-work-with-the-c-standard-library-headers

**Comment by rdnetto** [comment]
To summarise the [upstream issue](https://github.com/Valloric/YouCompleteMe/issues/303), the problem is that the logic for generating standard library paths lives in the `clang` executable instead of libclang. According to [this Stack Overflow post](http://stackoverflow.com/questions/11946294/dump-include-paths-from-g), you can get those paths using this command:

```
clang++ -E -x c++ - -v < /dev/null
```

I'm not going to add any logic to automatically add those paths though, because that would break generation for more sophisticated systems, such as cmake, which usually state those dependencies explicitly. Besides, my official position has always been that YCM-Gen does not aim to generate a config file that is 100% perfect, but one that is 99% of the way there and may need some minor fix ups.

That said, what I can do is tell you how to alter the template config file used by YCM-Gen. (Just be aware that I will **not** support it, since it's extremely likely that hardcoding flags will eventually break generation for some program.)
- run `git -C ~/.vim/bundle/YCM-Generator config -e` and add `rebase = true` to the section for the stable branch
- edit `~/.vim/bundle/YCM-Generator/template.py` and add the default flags. I suggest adding comments to indicate which flags are hardcoded and which are auto-generated. Do **not** remove the line `# INSERT FLAGS HERE`, because YCM-Gen relies on it to know where to insert the flags
- commit your changes with `git commit -a`. This will ensure that when you update YCM-Gen, your changes will automatically be rebased on top of the latest version.

**Comment by agauniyal** [comment]
Thanks a ton :+1:

**Comment by rdnetto** [comment]
No problem :)
