### ISSUE TITLE
Add branch master to be the same as stable

### ISSUE THREAD

**Issue by incertia** [rdnetto/YCM-Generator#54]
This makes it easy to update all submodules with `git submodule update --recursive --remote`

**Comment by rdnetto** [comment]
Unfortunately, I don't think this is a good idea. Putting aside that remembering to manually update an aliased branch would be error prone, there used to be a branch called `master` which served the role currently performed by `develop`. I created `develop` and `stable` to make the distinction clearer (I was strongly influenced by git-flow at the time), but only deleted the master branch relatively recently (in the last year or so). That means that it's not unlikely that there are users who still have that branch checked out, and could accidentally end up on a different branch to what they intended.

I'm not sure why you're using submodules instead of a plugin manager (Pathogen user?), but you can easily configure git to track a specific branch with [`submodule.<name>.branch`](https://git-scm.com/docs/gitmodules).
