### ISSUE TITLE
Generate include path with absolute system path

### ISSUE THREAD

**Issue by david-wang-2015** [rdnetto/YCM-Generator#60]
This tool is very convenient to generate the '.ycm_extra_conf.py' file.
In most of the case, this file should be placed in the root path with the project source code.
However, I have a requirement that put this file to the upper-level folder.
So YCM could not get the correct place for the include file specified by "-I" because it's not the absolute path.
Is there any possibility that adds a parameter to define if the path in the flags is relative or absolute?
Thanks.

**Comment by rdnetto** [comment]
The problem is that all YCM-Gen does is collect the arguments that the build system (e.g. make) passes to the compiler. This means that we'd need to recognize which arguments include paths/filenames in order to apply the appropriate transformation to them. While we do already have some logic for identifying filenames/paths (`filename_flags` at line 343), this wouldn't be a complete solution, because it's quite common to omit the space between certain flags and their arguments. e.g. `-o foo` and `-ofoo` are equivalent. Distinguishing between those cases and completely different arguments would be quite complex, enough so that I'm not going to attempt to implement it right now. (Though I'd be happy to accept a PR that solved the problem sufficiently well.)

Furthermore, the goal of this project is not to generate a `.ycm_extra_conf.py` file that is 100% perfect - some manual adjustments will be needed in some cases. In your case it should be doable fairly easily with a global search and replace, or by inserting the appropriate prefix to all the path flags.

(Sorry for the delay in responding - the email got buried in my inbox.)
