### ISSUE TITLE
no python2 in macOS 10.12

### ISSUE THREAD

**Issue by meritozh** [rdnetto/YCM-Generator#85]
No `python2` executable  file in `/usr/bin` in macOS 10.12.

Maybe you should use shebang with `python` or `python2.7`

**Comment by ssfdust** [comment]
I think it could be better that you create a symbolic link for python2 yourself.

**Comment by rdnetto** [comment]
The Python website recommends using `python` for Python 2, and `python3` for Python 3. I can't find any docs on their website recommending `python2` - this seems to be something that some Linux distros do just to fix an obvious omission. (It's also worth noting that Arch symlinks `python` to `python3`, for added fun.)

Given that it's extremely unlikely there's going to be a Python 2.8, I'm just going to use `python2.7` to make everyone's life easier.

**Comment by meritozh** [comment]
Another suggestion: how about add this function to templete.py?

https://github.com/Valloric/YouCompleteMe/issues/2330#issuecomment-252546664 https://github.com/Valloric/YouCompleteMe/issues/2330#issuecomment-252546664

**Comment by rdnetto** [comment]
> Another suggestion: how about add this function to templete.py?

First of all, in the future please create new issues to track separate bugs / feature requests instead of re-using existing ones.

Secondly, there isn't any clear response on Valloric/YouCompleteMe#2330 about the direction YCM is going to take. I'd like to hold off on merging a workaround for this until we know what they're doing.
